### ISSUE TITLE
How to Remove *app* container taking 1 full CPU

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [mythrantic/ollama-docker#44]
**Describe the bug**
Do we have any way to not have this *-app* container taking up 100% of one of my CPU core ?
Even if commented from docker compose file, it's still created :(

**To Reproduce**
docker compose up / docker compose stats

**Expected behavior**
Not having app container, not having 1 CPU in full load because of a frontend which is probably not mandatory to openwebui/ollama?

**Screenshots**
![Image](https://github.com/user-attachments/assets/55422fbd-a517-446a-84ed-c495dcf5e74e)

**Comment by BetterToAutomateTheWorld** [comment]
Hi @valiantlynx,

Thank you for your quick reply! 
As stated in my initial message, commenting the `app` part in the docker compose file, doesn't change anything.

i'm running this compose file:
```
 % cat docker-compose.yml
services:
  #  app:
  #    build: .
  #    ports:
  #      - 8000:8000
  #      - 5678:5678
  #    volumes:
  #      - .:/code
  #    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
  #    restart: always
  #    depends_on:
  #      - ollama
  #      - ollama-webui
  #    networks:
  #      - ollama-docker

  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=10m # Duration string (such as "10m" or "24h")
      - OLLAMA_MAX_LOADED_MODELS=1 # The maximum number of models that can be loaded concurrently provided they fit in available memory. The default is 3 * the number of GPUs or 3 for CPU inference.
      #- OLLAMA_NUM_PARALLEL=1 # The maximum number of parallel requests each model will process at the same time. The default will auto-select either 4 or 1 based on available memory.
      #- OLLAMA_MAX_QUEUE # The maximum number of requests Ollama will queue when busy before rejecting additional requests. The default is 512
      #- OLLAMA_KV_CACHE_TYPE=f16 # The quantization type for the K/V cache. Default is f16. Could be q8_0 or q4_0.
      #- OLLAMA_FLASH_ATTENTION=1 # Only if using dGPU Nvidia with CUDA. Improve memory usage/reduce it.
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - ENV=prod # set 'dev' to get /docs endpoint, which serves up an interactive API documentation interface powered by Swagger UI
      - WEBUI_AUTH=True
      #- WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://192.168.1.202:8080
      - WEBUI_SECRET_KEY=XYZ
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
```

and launching it, as CPU only, using:
```
docker compose up -d
```
